### ISSUE TITLE
Small Performance change

### ISSUE THREAD

**Issue by ghost** [stonehippo/CircuitPython_Bela_Trill#1]
HI STonehippo,
thanks for the project, saved me a lot of time getting my Pi PIco with Trill up and running for Midi Comms.
Just a small remark. I have 5 bars, thus reading them takes a lot of time. I ended up changing the command function as follows, moving the time.sleep into the buffer read, to avoid waiting, when there is no buffer requested.

```
def command(self, cmd, buffer_size=32) -> bytearray:
        buffer = bytearray(buffer_size)
        with self.i2c_device as trill:
            trill.write(cmd)
            if buffer_size > 0:
                time.sleep(0.025)
                trill.readinto(buffer)
            return buffer
```

Now during a normal read, it does not wait, which is much faster. Maybe of interest to you ;-)

**Comment by stonehippo** [comment]
Thanks, good call. I've made this change in [e8fb9ab](https://github.com/stonehippo/CircuitPython_Bela_Trill/commit/e8fb9abc895c052697d5bcf9648848b5fb62623c).
